### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by RockyNiu** [JacksonTian/sync_package#13]
本地没有用户名密码

Sync package sync_package from http://isaacs.iriscouch.com/registry/ to http://127.0.0.1/registry/

Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)

**Comment by JacksonTian** [comment]
推荐去使用cnpm。

**Comment by RockyNiu** [comment]
好的，可以在home server上试试。
本来想给公司建一个private registry，跟着您的教程（加参考https://github.com/npm/npm-registry-couchapp） 已经建好了，但是replicating的时候出了问题，于是就create了这个issue。

但是刚刚发现Nexus有npm的plugin，公司就要求用Nexus的了。

**Comment by JacksonTian** [comment]
不是用户名密码的问题，auth部分，在日志中被我故意抹去了。安全相关。

**Comment by RockyNiu** [comment]
好的，谢谢。请问cnpm有计划做bower的private registry mirror工具吗？private-bower等实际上只是一个public registry的proxy，并不能在本地同步official bower registry.

**Comment by JacksonTian** [comment]
cnpm与npm完全兼容的。

**Comment by RockyNiu** [comment]
可能我没有说清楚，我说的是bower的registry https://bower.herokuapp.com 不是npm 的 http://registry.npmjs.org/

我的理解是，bower自己有一个registry，跟npm不是完全相同的，bower更注重前端的repo，npm更宽泛。

**Comment by JacksonTian** [comment]
没有研究过bower ＝ ＝ 如果理论上bower用的就是npm registry的话，cnpm就能满足。
